
# This file is automatically generated, you probably don't want to edit this

compareovertimeOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "compareovertimeOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            indicators = NULL,
            stat_unit = NULL,
            time_column_long = NULL,
            is_long_format = NULL,
            number_periods = 1,
            time_column = "period",
            periods = NULL,
            polarity = NULL,
            ref = "list(ind1 = ref1, ind2=ref2, ...)",
            compute_ampi = FALSE,
            compute_mpi = FALSE,
            penalty = NULL,
            compute_harmonic_mean = FALSE,
            norm_harmonic_mean = "None",
            compute_geomean = FALSE,
            norm_geomean = "None",
            compute_mean = FALSE,
            norm_mean = "None",
            compute_quadratic_mean = FALSE,
            norm_quadratic_mean = "None",
            saving_path = NULL, ...) {

            super$initialize(
                package="CompositeIndicator",
                name="compareovertime",
                requiresData=TRUE,
                ...)

            private$..indicators <- jmvcore::OptionVariables$new(
                "indicators",
                indicators)
            private$..stat_unit <- jmvcore::OptionVariable$new(
                "stat_unit",
                stat_unit)
            private$..time_column_long <- jmvcore::OptionVariable$new(
                "time_column_long",
                time_column_long)
            private$..is_long_format <- jmvcore::OptionString$new(
                "is_long_format",
                is_long_format)
            private$..number_periods <- jmvcore::OptionInteger$new(
                "number_periods",
                number_periods,
                default=1)
            private$..time_column <- jmvcore::OptionString$new(
                "time_column",
                time_column,
                default="period")
            private$..periods <- jmvcore::OptionString$new(
                "periods",
                periods)
            private$..polarity <- jmvcore::OptionString$new(
                "polarity",
                polarity)
            private$..ref <- jmvcore::OptionString$new(
                "ref",
                ref,
                default="list(ind1 = ref1, ind2=ref2, ...)")
            private$..compute_ampi <- jmvcore::OptionBool$new(
                "compute_ampi",
                compute_ampi,
                default=FALSE)
            private$..compute_mpi <- jmvcore::OptionBool$new(
                "compute_mpi",
                compute_mpi,
                default=FALSE)
            private$..penalty <- jmvcore::OptionList$new(
                "penalty",
                penalty,
                options=list(
                    "POS",
                    "NEG"))
            private$..compute_harmonic_mean <- jmvcore::OptionBool$new(
                "compute_harmonic_mean",
                compute_harmonic_mean,
                default=FALSE)
            private$..norm_harmonic_mean <- jmvcore::OptionList$new(
                "norm_harmonic_mean",
                norm_harmonic_mean,
                options=list(
                    "None",
                    "1, Standardization",
                    "2, Min-max",
                    "3, Ranking"),
                default="None")
            private$..compute_geomean <- jmvcore::OptionBool$new(
                "compute_geomean",
                compute_geomean,
                default=FALSE)
            private$..norm_geomean <- jmvcore::OptionList$new(
                "norm_geomean",
                norm_geomean,
                options=list(
                    "None",
                    "1, Standardization",
                    "2, Min-max",
                    "3, Ranking"),
                default="None")
            private$..compute_mean <- jmvcore::OptionBool$new(
                "compute_mean",
                compute_mean,
                default=FALSE)
            private$..norm_mean <- jmvcore::OptionList$new(
                "norm_mean",
                norm_mean,
                options=list(
                    "None",
                    "1, Standardization",
                    "2, Min-max",
                    "3, Ranking"),
                default="None")
            private$..compute_quadratic_mean <- jmvcore::OptionBool$new(
                "compute_quadratic_mean",
                compute_quadratic_mean,
                default=FALSE)
            private$..norm_quadratic_mean <- jmvcore::OptionList$new(
                "norm_quadratic_mean",
                norm_quadratic_mean,
                options=list(
                    "None",
                    "1, Standardization",
                    "2, Min-max",
                    "3, Ranking"),
                default="None")
            private$..saving_path <- jmvcore::OptionString$new(
                "saving_path",
                saving_path)
            private$..composite_indicators <- jmvcore::OptionOutput$new(
                "composite_indicators")

            self$.addOption(private$..indicators)
            self$.addOption(private$..stat_unit)
            self$.addOption(private$..time_column_long)
            self$.addOption(private$..is_long_format)
            self$.addOption(private$..number_periods)
            self$.addOption(private$..time_column)
            self$.addOption(private$..periods)
            self$.addOption(private$..polarity)
            self$.addOption(private$..ref)
            self$.addOption(private$..compute_ampi)
            self$.addOption(private$..compute_mpi)
            self$.addOption(private$..penalty)
            self$.addOption(private$..compute_harmonic_mean)
            self$.addOption(private$..norm_harmonic_mean)
            self$.addOption(private$..compute_geomean)
            self$.addOption(private$..norm_geomean)
            self$.addOption(private$..compute_mean)
            self$.addOption(private$..norm_mean)
            self$.addOption(private$..compute_quadratic_mean)
            self$.addOption(private$..norm_quadratic_mean)
            self$.addOption(private$..saving_path)
            self$.addOption(private$..composite_indicators)
        }),
    active = list(
        indicators = function() private$..indicators$value,
        stat_unit = function() private$..stat_unit$value,
        time_column_long = function() private$..time_column_long$value,
        is_long_format = function() private$..is_long_format$value,
        number_periods = function() private$..number_periods$value,
        time_column = function() private$..time_column$value,
        periods = function() private$..periods$value,
        polarity = function() private$..polarity$value,
        ref = function() private$..ref$value,
        compute_ampi = function() private$..compute_ampi$value,
        compute_mpi = function() private$..compute_mpi$value,
        penalty = function() private$..penalty$value,
        compute_harmonic_mean = function() private$..compute_harmonic_mean$value,
        norm_harmonic_mean = function() private$..norm_harmonic_mean$value,
        compute_geomean = function() private$..compute_geomean$value,
        norm_geomean = function() private$..norm_geomean$value,
        compute_mean = function() private$..compute_mean$value,
        norm_mean = function() private$..norm_mean$value,
        compute_quadratic_mean = function() private$..compute_quadratic_mean$value,
        norm_quadratic_mean = function() private$..norm_quadratic_mean$value,
        saving_path = function() private$..saving_path$value,
        composite_indicators = function() private$..composite_indicators$value),
    private = list(
        ..indicators = NA,
        ..stat_unit = NA,
        ..time_column_long = NA,
        ..is_long_format = NA,
        ..number_periods = NA,
        ..time_column = NA,
        ..periods = NA,
        ..polarity = NA,
        ..ref = NA,
        ..compute_ampi = NA,
        ..compute_mpi = NA,
        ..penalty = NA,
        ..compute_harmonic_mean = NA,
        ..norm_harmonic_mean = NA,
        ..compute_geomean = NA,
        ..norm_geomean = NA,
        ..compute_mean = NA,
        ..norm_mean = NA,
        ..compute_quadratic_mean = NA,
        ..norm_quadratic_mean = NA,
        ..saving_path = NA,
        ..composite_indicators = NA)
)

compareovertimeResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "compareovertimeResults",
    inherit = jmvcore::Group,
    active = list(
        getting_started = function() private$.items[["getting_started"]],
        CI_table = function() private$.items[["CI_table"]],
        composite_indicators = function() private$.items[["composite_indicators"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Compare composite indicators over time")
            self$add(jmvcore::Html$new(
                options=options,
                name="getting_started",
                title="Getting started"))
            self$add(jmvcore::Table$new(
                options=options,
                name="CI_table",
                title="CI scores",
                rows=0,
                columns=list(
                    list(
                        `name`="ID", 
                        `type`="integer"))))
            self$add(jmvcore::Output$new(
                options=options,
                name="composite_indicators",
                title="CompositeIndicators",
                varTitle="CI",
                measureType="continuous",
                varDescription="Composite indicators results",
                items="(number_periods  * 12)"))}))

compareovertimeBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "compareovertimeBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "CompositeIndicator",
                name = "compareovertime",
                version = c(1,0,0),
                options = options,
                results = compareovertimeResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'none')
        }))

#' Compare composite indicators over time
#'
#' 
#' @param data .
#' @param indicators .
#' @param stat_unit .
#' @param time_column_long .
#' @param is_long_format .
#' @param number_periods .
#' @param time_column .
#' @param periods .
#' @param polarity .
#' @param ref .
#' @param compute_ampi .
#' @param compute_mpi .
#' @param penalty .
#' @param compute_harmonic_mean .
#' @param norm_harmonic_mean .
#' @param compute_geomean .
#' @param norm_geomean .
#' @param compute_mean .
#' @param norm_mean .
#' @param compute_quadratic_mean .
#' @param norm_quadratic_mean .
#' @param saving_path .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$getting_started} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$CI_table} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$composite_indicators} \tab \tab \tab \tab \tab an output \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$CI_table$asDF}
#'
#' \code{as.data.frame(results$CI_table)}
#'
#' @export
compareovertime <- function(
    data,
    indicators,
    stat_unit,
    time_column_long,
    is_long_format,
    number_periods = 1,
    time_column = "period",
    periods,
    polarity,
    ref = "list(ind1 = ref1, ind2=ref2, ...)",
    compute_ampi = FALSE,
    compute_mpi = FALSE,
    penalty,
    compute_harmonic_mean = FALSE,
    norm_harmonic_mean = "None",
    compute_geomean = FALSE,
    norm_geomean = "None",
    compute_mean = FALSE,
    norm_mean = "None",
    compute_quadratic_mean = FALSE,
    norm_quadratic_mean = "None",
    saving_path) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("compareovertime requires jmvcore to be installed (restart may be required)")

    if ( ! missing(indicators)) indicators <- jmvcore::resolveQuo(jmvcore::enquo(indicators))
    if ( ! missing(stat_unit)) stat_unit <- jmvcore::resolveQuo(jmvcore::enquo(stat_unit))
    if ( ! missing(time_column_long)) time_column_long <- jmvcore::resolveQuo(jmvcore::enquo(time_column_long))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(indicators), indicators, NULL),
            `if`( ! missing(stat_unit), stat_unit, NULL),
            `if`( ! missing(time_column_long), time_column_long, NULL))


    options <- compareovertimeOptions$new(
        indicators = indicators,
        stat_unit = stat_unit,
        time_column_long = time_column_long,
        is_long_format = is_long_format,
        number_periods = number_periods,
        time_column = time_column,
        periods = periods,
        polarity = polarity,
        ref = ref,
        compute_ampi = compute_ampi,
        compute_mpi = compute_mpi,
        penalty = penalty,
        compute_harmonic_mean = compute_harmonic_mean,
        norm_harmonic_mean = norm_harmonic_mean,
        compute_geomean = compute_geomean,
        norm_geomean = norm_geomean,
        compute_mean = compute_mean,
        norm_mean = norm_mean,
        compute_quadratic_mean = compute_quadratic_mean,
        norm_quadratic_mean = norm_quadratic_mean,
        saving_path = saving_path)

    analysis <- compareovertimeClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

