
# This file is automatically generated, you probably don't want to edit this

mapsOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mapsOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            stat_unit = NULL,
            map_fill_variables = NULL,
            shape_file_path = NULL,
            shape_file = NULL,
            stat_unit_name_shp = NULL,
            stat_unit_shp_to_remove = "",
            saving_path = NULL,
            map_output_format = NULL,
            plot_width = 10,
            plot_height = 10, ...) {

            super$initialize(
                package="CompositeIndicator",
                name="maps",
                requiresData=TRUE,
                ...)

            private$..stat_unit <- jmvcore::OptionVariable$new(
                "stat_unit",
                stat_unit)
            private$..map_fill_variables <- jmvcore::OptionVariables$new(
                "map_fill_variables",
                map_fill_variables)
            private$..shape_file_path <- jmvcore::OptionString$new(
                "shape_file_path",
                shape_file_path)
            private$..shape_file <- jmvcore::OptionString$new(
                "shape_file",
                shape_file)
            private$..stat_unit_name_shp <- jmvcore::OptionString$new(
                "stat_unit_name_shp",
                stat_unit_name_shp)
            private$..stat_unit_shp_to_remove <- jmvcore::OptionString$new(
                "stat_unit_shp_to_remove",
                stat_unit_shp_to_remove,
                default="")
            private$..saving_path <- jmvcore::OptionString$new(
                "saving_path",
                saving_path)
            private$..map_output_format <- jmvcore::OptionString$new(
                "map_output_format",
                map_output_format)
            private$..plot_width <- jmvcore::OptionInteger$new(
                "plot_width",
                plot_width,
                default=10)
            private$..plot_height <- jmvcore::OptionInteger$new(
                "plot_height",
                plot_height,
                default=10)

            self$.addOption(private$..stat_unit)
            self$.addOption(private$..map_fill_variables)
            self$.addOption(private$..shape_file_path)
            self$.addOption(private$..shape_file)
            self$.addOption(private$..stat_unit_name_shp)
            self$.addOption(private$..stat_unit_shp_to_remove)
            self$.addOption(private$..saving_path)
            self$.addOption(private$..map_output_format)
            self$.addOption(private$..plot_width)
            self$.addOption(private$..plot_height)
        }),
    active = list(
        stat_unit = function() private$..stat_unit$value,
        map_fill_variables = function() private$..map_fill_variables$value,
        shape_file_path = function() private$..shape_file_path$value,
        shape_file = function() private$..shape_file$value,
        stat_unit_name_shp = function() private$..stat_unit_name_shp$value,
        stat_unit_shp_to_remove = function() private$..stat_unit_shp_to_remove$value,
        saving_path = function() private$..saving_path$value,
        map_output_format = function() private$..map_output_format$value,
        plot_width = function() private$..plot_width$value,
        plot_height = function() private$..plot_height$value),
    private = list(
        ..stat_unit = NA,
        ..map_fill_variables = NA,
        ..shape_file_path = NA,
        ..shape_file = NA,
        ..stat_unit_name_shp = NA,
        ..stat_unit_shp_to_remove = NA,
        ..saving_path = NA,
        ..map_output_format = NA,
        ..plot_width = NA,
        ..plot_height = NA)
)

mapsResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mapsResults",
    inherit = jmvcore::Group,
    active = list(
        check = function() private$.items[["check"]],
        getting_started = function() private$.items[["getting_started"]],
        plots = function() private$.items[["plots"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Maps")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="check",
                title="check"))
            self$add(jmvcore::Html$new(
                options=options,
                name="getting_started",
                title="Getting started"))
            self$add(jmvcore::Array$new(
                options=options,
                name="plots",
                title="Plots",
                items="(map_fill_variables)",
                template=jmvcore::Image$new(
                    options=options,
                    title="$key",
                    width=600,
                    height=400,
                    renderFun=".plot")))}))

mapsBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mapsBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "CompositeIndicator",
                name = "maps",
                version = c(1,0,0),
                options = options,
                results = mapsResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Maps
#'
#' 
#' @param data .
#' @param stat_unit .
#' @param map_fill_variables .
#' @param shape_file_path .
#' @param shape_file .
#' @param stat_unit_name_shp .
#' @param stat_unit_shp_to_remove .
#' @param saving_path .
#' @param map_output_format .
#' @param plot_width .
#' @param plot_height .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$check} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$getting_started} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$plots} \tab \tab \tab \tab \tab an array of plots \cr
#' }
#'
#' @export
maps <- function(
    data,
    stat_unit,
    map_fill_variables,
    shape_file_path,
    shape_file,
    stat_unit_name_shp,
    stat_unit_shp_to_remove = "",
    saving_path,
    map_output_format,
    plot_width = 10,
    plot_height = 10) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("maps requires jmvcore to be installed (restart may be required)")

    if ( ! missing(stat_unit)) stat_unit <- jmvcore::resolveQuo(jmvcore::enquo(stat_unit))
    if ( ! missing(map_fill_variables)) map_fill_variables <- jmvcore::resolveQuo(jmvcore::enquo(map_fill_variables))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(stat_unit), stat_unit, NULL),
            `if`( ! missing(map_fill_variables), map_fill_variables, NULL))


    options <- mapsOptions$new(
        stat_unit = stat_unit,
        map_fill_variables = map_fill_variables,
        shape_file_path = shape_file_path,
        shape_file = shape_file,
        stat_unit_name_shp = stat_unit_name_shp,
        stat_unit_shp_to_remove = stat_unit_shp_to_remove,
        saving_path = saving_path,
        map_output_format = map_output_format,
        plot_width = plot_width,
        plot_height = plot_height)

    analysis <- mapsClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

