
# This file is automatically generated, you probably don't want to edit this

meanOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "meanOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            indicators = NULL,
            stat_unit = NULL,
            polarity = NULL,
            normalization = "None",
            p = "1",
            saving_path = NULL, ...) {

            super$initialize(
                package="CompositeIndicator",
                name="mean",
                requiresData=TRUE,
                ...)

            private$..indicators <- jmvcore::OptionVariables$new(
                "indicators",
                indicators)
            private$..stat_unit <- jmvcore::OptionVariable$new(
                "stat_unit",
                stat_unit)
            private$..polarity <- jmvcore::OptionString$new(
                "polarity",
                polarity)
            private$..normalization <- jmvcore::OptionList$new(
                "normalization",
                normalization,
                options=list(
                    "None",
                    "1, Standardization",
                    "2, Min-max",
                    "3, Ranking"),
                default="None")
            private$..p <- jmvcore::OptionList$new(
                "p",
                p,
                options=list(
                    "-1",
                    "0",
                    "1",
                    "2"),
                default="1")
            private$..saving_path <- jmvcore::OptionString$new(
                "saving_path",
                saving_path)

            self$.addOption(private$..indicators)
            self$.addOption(private$..stat_unit)
            self$.addOption(private$..polarity)
            self$.addOption(private$..normalization)
            self$.addOption(private$..p)
            self$.addOption(private$..saving_path)
        }),
    active = list(
        indicators = function() private$..indicators$value,
        stat_unit = function() private$..stat_unit$value,
        polarity = function() private$..polarity$value,
        normalization = function() private$..normalization$value,
        p = function() private$..p$value,
        saving_path = function() private$..saving_path$value),
    private = list(
        ..indicators = NA,
        ..stat_unit = NA,
        ..polarity = NA,
        ..normalization = NA,
        ..p = NA,
        ..saving_path = NA)
)

meanResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "meanResults",
    inherit = jmvcore::Group,
    active = list(
        getting_started = function() private$.items[["getting_started"]],
        CI_table = function() private$.items[["CI_table"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Generalized mean")
            self$add(jmvcore::Html$new(
                options=options,
                name="getting_started",
                title="Getting started"))
            self$add(jmvcore::Table$new(
                options=options,
                name="CI_table",
                title="Mean scores and ranking",
                rows=0,
                columns=list(
                    list(
                        `name`="ID", 
                        `type`="integer"))))}))

meanBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "meanBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "CompositeIndicator",
                name = "mean",
                version = c(1,0,0),
                options = options,
                results = meanResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Generalized mean
#'
#' 
#' @param data .
#' @param indicators .
#' @param stat_unit .
#' @param polarity .
#' @param normalization .
#' @param p .
#' @param saving_path .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$getting_started} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$CI_table} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$CI_table$asDF}
#'
#' \code{as.data.frame(results$CI_table)}
#'
#' @export
mean <- function(
    data,
    indicators,
    stat_unit,
    polarity,
    normalization = "None",
    p = "1",
    saving_path) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("mean requires jmvcore to be installed (restart may be required)")

    if ( ! missing(indicators)) indicators <- jmvcore::resolveQuo(jmvcore::enquo(indicators))
    if ( ! missing(stat_unit)) stat_unit <- jmvcore::resolveQuo(jmvcore::enquo(stat_unit))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(indicators), indicators, NULL),
            `if`( ! missing(stat_unit), stat_unit, NULL))


    options <- meanOptions$new(
        indicators = indicators,
        stat_unit = stat_unit,
        polarity = polarity,
        normalization = normalization,
        p = p,
        saving_path = saving_path)

    analysis <- meanClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

