
# This file is automatically generated, you probably don't want to edit this

mpiOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mpiOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            indicators = NULL,
            stat_unit = NULL,
            polarity = NULL,
            penalty = NULL,
            saving_path = NULL, ...) {

            super$initialize(
                package="CompositeIndicator",
                name="mpi",
                requiresData=TRUE,
                ...)

            private$..indicators <- jmvcore::OptionVariables$new(
                "indicators",
                indicators)
            private$..stat_unit <- jmvcore::OptionVariable$new(
                "stat_unit",
                stat_unit)
            private$..polarity <- jmvcore::OptionString$new(
                "polarity",
                polarity)
            private$..penalty <- jmvcore::OptionList$new(
                "penalty",
                penalty,
                options=list(
                    "POS",
                    "NEG"))
            private$..saving_path <- jmvcore::OptionString$new(
                "saving_path",
                saving_path)

            self$.addOption(private$..indicators)
            self$.addOption(private$..stat_unit)
            self$.addOption(private$..polarity)
            self$.addOption(private$..penalty)
            self$.addOption(private$..saving_path)
        }),
    active = list(
        indicators = function() private$..indicators$value,
        stat_unit = function() private$..stat_unit$value,
        polarity = function() private$..polarity$value,
        penalty = function() private$..penalty$value,
        saving_path = function() private$..saving_path$value),
    private = list(
        ..indicators = NA,
        ..stat_unit = NA,
        ..polarity = NA,
        ..penalty = NA,
        ..saving_path = NA)
)

mpiResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mpiResults",
    inherit = jmvcore::Group,
    active = list(
        getting_started = function() private$.items[["getting_started"]],
        data_scores = function() private$.items[["data_scores"]],
        CI_table = function() private$.items[["CI_table"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Mazziotta-Pareto Index")
            self$add(jmvcore::Html$new(
                options=options,
                name="getting_started",
                title="Getting started"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="data_scores",
                title="View the first 50 rows"))
            self$add(jmvcore::Table$new(
                options=options,
                name="CI_table",
                title="Mazziotta-Pareto Index scores and ranking",
                rows=0,
                columns=list(
                    list(
                        `name`="ID", 
                        `type`="integer"))))}))

mpiBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mpiBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "CompositeIndicator",
                name = "mpi",
                version = c(1,0,0),
                options = options,
                results = mpiResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Mazziotta-Pareto Index
#'
#' 
#' @param data .
#' @param indicators .
#' @param stat_unit .
#' @param polarity .
#' @param penalty .
#' @param saving_path .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$getting_started} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$data_scores} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$CI_table} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$CI_table$asDF}
#'
#' \code{as.data.frame(results$CI_table)}
#'
#' @export
mpi <- function(
    data,
    indicators,
    stat_unit,
    polarity,
    penalty,
    saving_path) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("mpi requires jmvcore to be installed (restart may be required)")

    if ( ! missing(indicators)) indicators <- jmvcore::resolveQuo(jmvcore::enquo(indicators))
    if ( ! missing(stat_unit)) stat_unit <- jmvcore::resolveQuo(jmvcore::enquo(stat_unit))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(indicators), indicators, NULL),
            `if`( ! missing(stat_unit), stat_unit, NULL))


    options <- mpiOptions$new(
        indicators = indicators,
        stat_unit = stat_unit,
        polarity = polarity,
        penalty = penalty,
        saving_path = saving_path)

    analysis <- mpiClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

