
# This file is automatically generated, you probably don't want to edit this

ampiOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ampiOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            indicators = NULL,
            stat_unit = NULL,
            time_column_long = NULL,
            polarity = NULL,
            ref = "list(ind1 = ref1, ind2=ref2, ...)",
            penalty = "POS",
            open = NULL, ...) {

            super$initialize(
                package="CI",
                name="ampi",
                requiresData=TRUE,
                ...)

            private$..indicators <- jmvcore::OptionVariables$new(
                "indicators",
                indicators)
            private$..stat_unit <- jmvcore::OptionVariable$new(
                "stat_unit",
                stat_unit)
            private$..time_column_long <- jmvcore::OptionVariable$new(
                "time_column_long",
                time_column_long)
            private$..polarity <- jmvcore::OptionString$new(
                "polarity",
                polarity)
            private$..ref <- jmvcore::OptionString$new(
                "ref",
                ref,
                default="list(ind1 = ref1, ind2=ref2, ...)")
            private$..penalty <- jmvcore::OptionList$new(
                "penalty",
                penalty,
                options=list(
                    "POS",
                    "NEG"),
                default="POS")
            private$..open <- jmvcore::OptionAction$new(
                "open",
                open)

            self$.addOption(private$..indicators)
            self$.addOption(private$..stat_unit)
            self$.addOption(private$..time_column_long)
            self$.addOption(private$..polarity)
            self$.addOption(private$..ref)
            self$.addOption(private$..penalty)
            self$.addOption(private$..open)
        }),
    active = list(
        indicators = function() private$..indicators$value,
        stat_unit = function() private$..stat_unit$value,
        time_column_long = function() private$..time_column_long$value,
        polarity = function() private$..polarity$value,
        ref = function() private$..ref$value,
        penalty = function() private$..penalty$value,
        open = function() private$..open$value),
    private = list(
        ..indicators = NA,
        ..stat_unit = NA,
        ..time_column_long = NA,
        ..polarity = NA,
        ..ref = NA,
        ..penalty = NA,
        ..open = NA)
)

ampiResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ampiResults",
    inherit = jmvcore::Group,
    active = list(
        getting_started = function() private$.items[["getting_started"]],
        data_scores = function() private$.items[["data_scores"]],
        CI_table = function() private$.items[["CI_table"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Adjusted Mazziotta-Pareto Index")
            self$add(jmvcore::Html$new(
                options=options,
                name="getting_started",
                title="Getting started"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="data_scores",
                title="View the first 50 rows"))
            self$add(jmvcore::Table$new(
                options=options,
                name="CI_table",
                title="Adjusted Mazziotta-Pareto Index scores and ranking",
                rows=0,
                columns=list(
                    list(
                        `name`="ID", 
                        `type`="integer"))))}))

ampiBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ampiBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "CI",
                name = "ampi",
                version = c(1,0,0),
                options = options,
                results = ampiResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Adjusted Mazziotta-Pareto Index
#'
#' 
#' @param data .
#' @param indicators .
#' @param stat_unit .
#' @param time_column_long .
#' @param polarity .
#' @param ref .
#' @param penalty .
#' @param open .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$getting_started} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$data_scores} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$CI_table} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$CI_table$asDF}
#'
#' \code{as.data.frame(results$CI_table)}
#'
#' @export
ampi <- function(
    data,
    indicators,
    stat_unit,
    time_column_long,
    polarity,
    ref = "list(ind1 = ref1, ind2=ref2, ...)",
    penalty = "POS",
    open) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("ampi requires jmvcore to be installed (restart may be required)")

    if ( ! missing(indicators)) indicators <- jmvcore::resolveQuo(jmvcore::enquo(indicators))
    if ( ! missing(stat_unit)) stat_unit <- jmvcore::resolveQuo(jmvcore::enquo(stat_unit))
    if ( ! missing(time_column_long)) time_column_long <- jmvcore::resolveQuo(jmvcore::enquo(time_column_long))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(indicators), indicators, NULL),
            `if`( ! missing(stat_unit), stat_unit, NULL),
            `if`( ! missing(time_column_long), time_column_long, NULL))


    options <- ampiOptions$new(
        indicators = indicators,
        stat_unit = stat_unit,
        time_column_long = time_column_long,
        polarity = polarity,
        ref = ref,
        penalty = penalty,
        open = open)

    analysis <- ampiClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

