
# This file is automatically generated, you probably don't want to edit this

mapsOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mapsOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            stat_unit = NULL,
            map_fill_variables = NULL,
            latitude_min = NULL,
            latitude_max = NULL,
            longitude_min = NULL,
            longitude_max = NULL, ...) {

            super$initialize(
                package="CI",
                name="maps",
                requiresData=TRUE,
                ...)

            private$..stat_unit <- jmvcore::OptionVariable$new(
                "stat_unit",
                stat_unit)
            private$..map_fill_variables <- jmvcore::OptionVariables$new(
                "map_fill_variables",
                map_fill_variables)
            private$..latitude_min <- jmvcore::OptionNumber$new(
                "latitude_min",
                latitude_min)
            private$..latitude_max <- jmvcore::OptionNumber$new(
                "latitude_max",
                latitude_max)
            private$..longitude_min <- jmvcore::OptionNumber$new(
                "longitude_min",
                longitude_min)
            private$..longitude_max <- jmvcore::OptionNumber$new(
                "longitude_max",
                longitude_max)

            self$.addOption(private$..stat_unit)
            self$.addOption(private$..map_fill_variables)
            self$.addOption(private$..latitude_min)
            self$.addOption(private$..latitude_max)
            self$.addOption(private$..longitude_min)
            self$.addOption(private$..longitude_max)
        }),
    active = list(
        stat_unit = function() private$..stat_unit$value,
        map_fill_variables = function() private$..map_fill_variables$value,
        latitude_min = function() private$..latitude_min$value,
        latitude_max = function() private$..latitude_max$value,
        longitude_min = function() private$..longitude_min$value,
        longitude_max = function() private$..longitude_max$value),
    private = list(
        ..stat_unit = NA,
        ..map_fill_variables = NA,
        ..latitude_min = NA,
        ..latitude_max = NA,
        ..longitude_min = NA,
        ..longitude_max = NA)
)

mapsResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mapsResults",
    inherit = jmvcore::Group,
    active = list(
        getting_started = function() private$.items[["getting_started"]],
        plots = function() private$.items[["plots"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Maps")
            self$add(jmvcore::Html$new(
                options=options,
                name="getting_started",
                title="Getting started"))
            self$add(jmvcore::Array$new(
                options=options,
                name="plots",
                title="Plots",
                items="(map_fill_variables)",
                template=jmvcore::Image$new(
                    options=options,
                    title="$key",
                    width=600,
                    height=400,
                    renderFun=".plot")))}))

mapsBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mapsBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "CI",
                name = "maps",
                version = c(1,0,0),
                options = options,
                results = mapsResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Maps
#'
#' 
#' @param data .
#' @param stat_unit .
#' @param map_fill_variables .
#' @param latitude_min .
#' @param latitude_max .
#' @param longitude_min .
#' @param longitude_max .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$getting_started} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$plots} \tab \tab \tab \tab \tab an array of plots \cr
#' }
#'
#' @export
maps <- function(
    data,
    stat_unit,
    map_fill_variables,
    latitude_min,
    latitude_max,
    longitude_min,
    longitude_max) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("maps requires jmvcore to be installed (restart may be required)")

    if ( ! missing(stat_unit)) stat_unit <- jmvcore::resolveQuo(jmvcore::enquo(stat_unit))
    if ( ! missing(map_fill_variables)) map_fill_variables <- jmvcore::resolveQuo(jmvcore::enquo(map_fill_variables))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(stat_unit), stat_unit, NULL),
            `if`( ! missing(map_fill_variables), map_fill_variables, NULL))


    options <- mapsOptions$new(
        stat_unit = stat_unit,
        map_fill_variables = map_fill_variables,
        latitude_min = latitude_min,
        latitude_max = latitude_max,
        longitude_min = longitude_min,
        longitude_max = longitude_max)

    analysis <- mapsClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

